const currencyList = {
  Null: "",
  USD: "$",
  Euro: "€",
  Hrn: "₴",
  Pound_Sterling: "£",
  Yen: "¥",
  Franc: "₣",
  Rupee: "₹",
  Dinar: "د.ك",
  Dirham: "د",
  Riyal: "﷼",
  Mark: "₻",
  Ruouble: "₽",
  Lari: "₾",
  Lira: "₺",
  Manat: "₼",
  Tenge: "₸",
  Spesmilo: "₷",
  Baht: "฿",
  Won: "원",
  Dong: "₫",
  Tugrik: "₮",
  Drachma: "₯",
  Peso: "₱",
  Austral: "₳",
  Cedi: "₵",
  Guarani: "₲",
  Sheqel: "₪",
  Penny: "₰",
};
export type TcurrencyList = typeof currencyList;
export default currencyList;
